//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRestUnitTests.RestServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonResponse", Namespace="http://schemas.datacontract.org/2004/07/MyRESTService.Utils")]
    [System.SerializableAttribute()]
    public partial class JsonResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyRestUnitTests.RestServiceReference.Advertisement[] AdvertisementCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyRestUnitTests.RestServiceReference.Catagory[] CatagoryCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyRestUnitTests.RestServiceReference.Client[] ClientCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessFullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyRestUnitTests.RestServiceReference.Person[] PersonCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyRestUnitTests.RestServiceReference.Vehicle[] VehicleCollectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyRestUnitTests.RestServiceReference.Advertisement[] AdvertisementCollection {
            get {
                return this.AdvertisementCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.AdvertisementCollectionField, value) != true)) {
                    this.AdvertisementCollectionField = value;
                    this.RaisePropertyChanged("AdvertisementCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyRestUnitTests.RestServiceReference.Catagory[] CatagoryCollection {
            get {
                return this.CatagoryCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.CatagoryCollectionField, value) != true)) {
                    this.CatagoryCollectionField = value;
                    this.RaisePropertyChanged("CatagoryCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyRestUnitTests.RestServiceReference.Client[] ClientCollection {
            get {
                return this.ClientCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientCollectionField, value) != true)) {
                    this.ClientCollectionField = value;
                    this.RaisePropertyChanged("ClientCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessFull {
            get {
                return this.IsSuccessFullField;
            }
            set {
                if ((this.IsSuccessFullField.Equals(value) != true)) {
                    this.IsSuccessFullField = value;
                    this.RaisePropertyChanged("IsSuccessFull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyRestUnitTests.RestServiceReference.Person[] PersonCollection {
            get {
                return this.PersonCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonCollectionField, value) != true)) {
                    this.PersonCollectionField = value;
                    this.RaisePropertyChanged("PersonCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyRestUnitTests.RestServiceReference.Vehicle[] VehicleCollection {
            get {
                return this.VehicleCollectionField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleCollectionField, value) != true)) {
                    this.VehicleCollectionField = value;
                    this.RaisePropertyChanged("VehicleCollection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Advertisement", Namespace="http://schemas.datacontract.org/2004/07/MyRESTService.Models")]
    [System.SerializableAttribute()]
    public partial class Advertisement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((this.ExpiryDateField.Equals(value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Catagory", Namespace="http://schemas.datacontract.org/2004/07/MyRESTService.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyRestUnitTests.RestServiceReference.Vehicle))]
    public partial class Catagory : MyRestUnitTests.RestServiceReference.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CatagoryNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CatagoryName {
            get {
                return this.CatagoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CatagoryNameField, value) != true)) {
                    this.CatagoryNameField = value;
                    this.RaisePropertyChanged("CatagoryName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/MyRESTService.Models")]
    [System.SerializableAttribute()]
    public partial class Client : MyRestUnitTests.RestServiceReference.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactEmail {
            get {
                return this.ContactEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactEmailField, value) != true)) {
                    this.ContactEmailField = value;
                    this.RaisePropertyChanged("ContactEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPerson {
            get {
                return this.ContactPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonField, value) != true)) {
                    this.ContactPersonField = value;
                    this.RaisePropertyChanged("ContactPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPhone {
            get {
                return this.ContactPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPhoneField, value) != true)) {
                    this.ContactPhoneField = value;
                    this.RaisePropertyChanged("ContactPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PackageName {
            get {
                return this.PackageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageNameField, value) != true)) {
                    this.PackageNameField = value;
                    this.RaisePropertyChanged("PackageName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/MyRESTService.Models")]
    [System.SerializableAttribute()]
    public partial class Person : MyRestUnitTests.RestServiceReference.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanSendNotificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanSendNotification {
            get {
                return this.CanSendNotificationField;
            }
            set {
                if ((this.CanSendNotificationField.Equals(value) != true)) {
                    this.CanSendNotificationField = value;
                    this.RaisePropertyChanged("CanSendNotification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellNo {
            get {
                return this.CellNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CellNoField, value) != true)) {
                    this.CellNoField = value;
                    this.RaisePropertyChanged("CellNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationId {
            get {
                return this.RegistrationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationIdField, value) != true)) {
                    this.RegistrationIdField = value;
                    this.RaisePropertyChanged("RegistrationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicle", Namespace="http://schemas.datacontract.org/2004/07/MyRESTService.Models")]
    [System.SerializableAttribute()]
    public partial class Vehicle : MyRestUnitTests.RestServiceReference.Catagory {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Make {
            get {
                return this.MakeField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeField, value) != true)) {
                    this.MakeField = value;
                    this.RaisePropertyChanged("Make");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleType {
            get {
                return this.VehicleTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleTypeField, value) != true)) {
                    this.VehicleTypeField = value;
                    this.RaisePropertyChanged("VehicleType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelBase", Namespace="http://schemas.datacontract.org/2004/07/MyRESTService.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyRestUnitTests.RestServiceReference.Client))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyRestUnitTests.RestServiceReference.Person))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyRestUnitTests.RestServiceReference.Catagory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyRestUnitTests.RestServiceReference.Vehicle))]
    public partial class ModelBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestServiceReference.IRestService")]
    public interface IRestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePerson/ViewAllPersons", ReplyAction="http://tempuri.org/IServicePerson/ViewAllPersonsResponse")]
        MyRestUnitTests.RestServiceReference.JsonResponse ViewAllPersons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePerson/ViewAllPersons", ReplyAction="http://tempuri.org/IServicePerson/ViewAllPersonsResponse")]
        System.Threading.Tasks.Task<MyRestUnitTests.RestServiceReference.JsonResponse> ViewAllPersonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePerson/AddPerson", ReplyAction="http://tempuri.org/IServicePerson/AddPersonResponse")]
        MyRestUnitTests.RestServiceReference.JsonResponse AddPerson(MyRestUnitTests.RestServiceReference.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePerson/AddPerson", ReplyAction="http://tempuri.org/IServicePerson/AddPersonResponse")]
        System.Threading.Tasks.Task<MyRestUnitTests.RestServiceReference.JsonResponse> AddPersonAsync(MyRestUnitTests.RestServiceReference.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdvertisement/ViewAllAdvertisements", ReplyAction="http://tempuri.org/IServiceAdvertisement/ViewAllAdvertisementsResponse")]
        MyRestUnitTests.RestServiceReference.JsonResponse ViewAllAdvertisements();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdvertisement/ViewAllAdvertisements", ReplyAction="http://tempuri.org/IServiceAdvertisement/ViewAllAdvertisementsResponse")]
        System.Threading.Tasks.Task<MyRestUnitTests.RestServiceReference.JsonResponse> ViewAllAdvertisementsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdvertisement/AddAdvertisement", ReplyAction="http://tempuri.org/IServiceAdvertisement/AddAdvertisementResponse")]
        MyRestUnitTests.RestServiceReference.JsonResponse AddAdvertisement(MyRestUnitTests.RestServiceReference.Advertisement advertisement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdvertisement/AddAdvertisement", ReplyAction="http://tempuri.org/IServiceAdvertisement/AddAdvertisementResponse")]
        System.Threading.Tasks.Task<MyRestUnitTests.RestServiceReference.JsonResponse> AddAdvertisementAsync(MyRestUnitTests.RestServiceReference.Advertisement advertisement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/ViewAllClients", ReplyAction="http://tempuri.org/IServiceClient/ViewAllClientsResponse")]
        MyRestUnitTests.RestServiceReference.JsonResponse ViewAllClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/ViewAllClients", ReplyAction="http://tempuri.org/IServiceClient/ViewAllClientsResponse")]
        System.Threading.Tasks.Task<MyRestUnitTests.RestServiceReference.JsonResponse> ViewAllClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/AddClient", ReplyAction="http://tempuri.org/IServiceClient/AddClientResponse")]
        MyRestUnitTests.RestServiceReference.JsonResponse AddClient(MyRestUnitTests.RestServiceReference.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClient/AddClient", ReplyAction="http://tempuri.org/IServiceClient/AddClientResponse")]
        System.Threading.Tasks.Task<MyRestUnitTests.RestServiceReference.JsonResponse> AddClientAsync(MyRestUnitTests.RestServiceReference.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatagory/ViewAllCatagories", ReplyAction="http://tempuri.org/IServiceCatagory/ViewAllCatagoriesResponse")]
        MyRestUnitTests.RestServiceReference.JsonResponse ViewAllCatagories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatagory/ViewAllCatagories", ReplyAction="http://tempuri.org/IServiceCatagory/ViewAllCatagoriesResponse")]
        System.Threading.Tasks.Task<MyRestUnitTests.RestServiceReference.JsonResponse> ViewAllCatagoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatagory/AddCatagory", ReplyAction="http://tempuri.org/IServiceCatagory/AddCatagoryResponse")]
        MyRestUnitTests.RestServiceReference.JsonResponse AddCatagory(MyRestUnitTests.RestServiceReference.Catagory catagory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatagory/AddCatagory", ReplyAction="http://tempuri.org/IServiceCatagory/AddCatagoryResponse")]
        System.Threading.Tasks.Task<MyRestUnitTests.RestServiceReference.JsonResponse> AddCatagoryAsync(MyRestUnitTests.RestServiceReference.Catagory catagory);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestServiceChannel : MyRestUnitTests.RestServiceReference.IRestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestServiceClient : System.ServiceModel.ClientBase<MyRestUnitTests.RestServiceReference.IRestService>, MyRestUnitTests.RestServiceReference.IRestService {
        
        public RestServiceClient() {
        }
        
        public RestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MyRestUnitTests.RestServiceReference.JsonResponse ViewAllPersons() {
            return base.Channel.ViewAllPersons();
        }
        
        public System.Threading.Tasks.Task<MyRestUnitTests.RestServiceReference.JsonResponse> ViewAllPersonsAsync() {
            return base.Channel.ViewAllPersonsAsync();
        }
        
        public MyRestUnitTests.RestServiceReference.JsonResponse AddPerson(MyRestUnitTests.RestServiceReference.Person person) {
            return base.Channel.AddPerson(person);
        }
        
        public System.Threading.Tasks.Task<MyRestUnitTests.RestServiceReference.JsonResponse> AddPersonAsync(MyRestUnitTests.RestServiceReference.Person person) {
            return base.Channel.AddPersonAsync(person);
        }
        
        public MyRestUnitTests.RestServiceReference.JsonResponse ViewAllAdvertisements() {
            return base.Channel.ViewAllAdvertisements();
        }
        
        public System.Threading.Tasks.Task<MyRestUnitTests.RestServiceReference.JsonResponse> ViewAllAdvertisementsAsync() {
            return base.Channel.ViewAllAdvertisementsAsync();
        }
        
        public MyRestUnitTests.RestServiceReference.JsonResponse AddAdvertisement(MyRestUnitTests.RestServiceReference.Advertisement advertisement) {
            return base.Channel.AddAdvertisement(advertisement);
        }
        
        public System.Threading.Tasks.Task<MyRestUnitTests.RestServiceReference.JsonResponse> AddAdvertisementAsync(MyRestUnitTests.RestServiceReference.Advertisement advertisement) {
            return base.Channel.AddAdvertisementAsync(advertisement);
        }
        
        public MyRestUnitTests.RestServiceReference.JsonResponse ViewAllClients() {
            return base.Channel.ViewAllClients();
        }
        
        public System.Threading.Tasks.Task<MyRestUnitTests.RestServiceReference.JsonResponse> ViewAllClientsAsync() {
            return base.Channel.ViewAllClientsAsync();
        }
        
        public MyRestUnitTests.RestServiceReference.JsonResponse AddClient(MyRestUnitTests.RestServiceReference.Client client) {
            return base.Channel.AddClient(client);
        }
        
        public System.Threading.Tasks.Task<MyRestUnitTests.RestServiceReference.JsonResponse> AddClientAsync(MyRestUnitTests.RestServiceReference.Client client) {
            return base.Channel.AddClientAsync(client);
        }
        
        public MyRestUnitTests.RestServiceReference.JsonResponse ViewAllCatagories() {
            return base.Channel.ViewAllCatagories();
        }
        
        public System.Threading.Tasks.Task<MyRestUnitTests.RestServiceReference.JsonResponse> ViewAllCatagoriesAsync() {
            return base.Channel.ViewAllCatagoriesAsync();
        }
        
        public MyRestUnitTests.RestServiceReference.JsonResponse AddCatagory(MyRestUnitTests.RestServiceReference.Catagory catagory) {
            return base.Channel.AddCatagory(catagory);
        }
        
        public System.Threading.Tasks.Task<MyRestUnitTests.RestServiceReference.JsonResponse> AddCatagoryAsync(MyRestUnitTests.RestServiceReference.Catagory catagory) {
            return base.Channel.AddCatagoryAsync(catagory);
        }
    }
}
